-----------------------------[
-- File fuzzy finder and more
-----------------------------]

local M = {
	-- "nvim-telescope/telescope.nvim",
	-- -- dependencies = { "nvim-telescope/telescope-ui-select.nvim" },
	-- lazy = true,
	-- cmd = "Telescope",
	-- keys = {
	-- 	{
	-- 		"\\",
	-- 		"<cmd>lua require('telescope.builtin').find_files(require('telescope.themes').get_dropdown{previewer = false})<cr>",
	-- 		desc = "fuzzy search",
	-- 	},
	-- 	{ "<leader>gc", "<cmd>Telescope git_commits<CR>", desc = "commits" },
	-- 	{ "<leader>gs", "<cmd>Telescope git_status<CR>", desc = "status" },
	-- 	{ "<leader>gb", "<cmd>Telescope git_branches<CR>", desc = "branch" },
	-- 	{ "<leader>l", "<cmd>Telescope live_grep<CR>", desc = "live grep" },
	-- 	{ "<leader>fb", "<cmd>Telescope buffers<CR>", desc = "buffer list" },
	-- },
	-- opts = {
	-- 	defaults = {
	-- 		prompt_prefix = " ",
	-- 		selection_caret = " ",
	-- 		path_display = { "smart" },
	-- 	},
	-- 	pickers = {
	-- 		find_files = {
	-- 			find_command = { "rg", "--files", "--hidden", "-g", "!.git" },
	-- 		},
	-- 	},
	-- },
	-- config = function(_, opts)
	-- 	local telescope = require("telescope")
	-- 	local actions = require("telescope.actions")
	--
	-- 	opts.mappings = {
	-- 		i = {
	-- 			["<C-n>"] = actions.cycle_history_next,
	-- 			["<C-p>"] = actions.cycle_history_prev,
	--
	-- 			["<C-j>"] = actions.move_selection_next,
	-- 			["<C-k>"] = actions.move_selection_previous,
	--
	-- 			["<C-c>"] = actions.close,
	--
	-- 			["<Down>"] = actions.move_selection_next,
	-- 			["<Up>"] = actions.move_selection_previous,
	--
	-- 			["<CR>"] = actions.select_default,
	-- 			["<C-x>"] = actions.select_horizontal,
	-- 			["<C-v>"] = actions.select_vertical,
	-- 			["<C-t>"] = actions.select_tab,
	--
	-- 			["<C-u>"] = actions.preview_scrolling_up,
	-- 			["<C-d>"] = actions.preview_scrolling_down,
	--
	-- 			["<PageUp>"] = actions.results_scrolling_up,
	-- 			["<PageDown>"] = actions.results_scrolling_down,
	--
	-- 			["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
	-- 			["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
	-- 			["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
	-- 			["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
	-- 			["<C-l>"] = actions.complete_tag,
	-- 			["<C-_>"] = actions.which_key, -- keys from pressing <C-/>
	-- 		},
	--
	-- 		n = {
	-- 			["<esc>"] = actions.close,
	-- 			["<CR>"] = actions.select_default,
	-- 			["<C-x>"] = actions.select_horizontal,
	-- 			["<C-v>"] = actions.select_vertical,
	-- 			["<C-t>"] = actions.select_tab,
	--
	-- 			["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
	-- 			["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
	-- 			["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
	-- 			["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
	--
	-- 			["j"] = actions.move_selection_next,
	-- 			["k"] = actions.move_selection_previous,
	-- 			["H"] = actions.move_to_top,
	-- 			["M"] = actions.move_to_middle,
	-- 			["L"] = actions.move_to_bottom,
	--
	-- 			["<Down>"] = actions.move_selection_next,
	-- 			["<Up>"] = actions.move_selection_previous,
	-- 			["gg"] = actions.move_to_top,
	-- 			["G"] = actions.move_to_bottom,
	--
	-- 			["<C-u>"] = actions.preview_scrolling_up,
	-- 			["<C-d>"] = actions.preview_scrolling_down,
	--
	-- 			["<PageUp>"] = actions.results_scrolling_up,
	-- 			["<PageDown>"] = actions.results_scrolling_down,
	--
	-- 			["?"] = actions.which_key,
	-- 		},
	-- 	}
	--
	-- 	opts.extensions = {
	-- 		-- ["ui-select"] = {
	-- 		--   require("telescope.themes").get_dropdown {}
	-- 		-- },
	-- 		media_files = {
	-- 			-- filetypes whitelist
	-- 			-- defaults to {"png", "jpg", "mp4", "webm", "pdf"}
	-- 			filetypes = { "png", "webp", "jpg", "jpeg", "svg" },
	-- 			find_cmd = "rg", -- find command (defaults to `fd`)
	-- 		},
	-- 	}
	--
	-- 	telescope.setup(opts)
	-- 	-- telescope.load_extension("ui-select")
	-- end,
}

return M
